### ISSUE TITLE
Some results don't link to original site

### ISSUE THREAD

**Issue by zcdunn** [capjamesg/indieweb-search#13]
I've found some search results that don't link to the result that they look like they should. Clicking these links takes me back to the search page. Here's an example link: https://indieweb-search.jamesg.blog/go?query=Gardening&page=2&r=https://thedimpau.se/2021/04/23/gardening-diary-rd.html

**Comment by capjamesg** [comment]
Hello @zcdunn! Thank you for your feedback. The initial intent behind the /go endpoint was to collect more data that could be used for relevance tuning in the future. However, this feature provides no immediate use to the user, and indeed was not functioning correctly.

I have removed the /go endpoint from the engine and deployed the code to production. All links will now go directly to the resource to which they are linking.

Thank you for spotting this issue! I love seeing feedback come in for the project!

Let me know if you have any other questions.
