### ISSUE TITLE
Search Fails on Certain Queries

### ISSUE THREAD

**Issue by zcdunn** [capjamesg/indieweb-search#51]
I'm getting a 500 response when searching for certain queries. Examples include "schema.org", "microdata", "rdf".

This may be unrelated but I get the same result when trying to use the _advanced search options_ (https://indieweb-search.jamesg.blog/advanced)

**Comment by zcdunn** [comment]
Hmm. After trying some more queries it seems all queries are failing for me right now

**Comment by capjamesg** [comment]
Thank you for your report @zcdunn. I had to restart Elasticsearch. I suspect that the OOM killer stopped the Elasticsearch process during the last crawl. Elasticsearch consumes a lot of memory and the server on which the project is running does not have a lot of memory left to give :)

I'm going to add a few queries at random to my uptime monitor so I can keep tabs on any potential issues with availability.

As for the /advanced page, it looks like there is a server issue. I'll review and respond with an update when I have one.

**Comment by capjamesg** [comment]
The advanced page should be working fine now.
